stages:
  - build_stag
  - build_prod
  - deploy_stag
  - deploy_prod

build_stag:
  image: node:alpine
  stage: build_stag
  only:
    - stage
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm install --force
    - CI=false
    - npm run build:stag
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/
    expire_in: 1 hour

build_prod:
  image: node:alpine
  stage: build_prod
  only:
    - main
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm install --force
    - CI=false
    - npm run build:prod
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/
    expire_in: 1 hour

deploy_stag:
  image: python:alpine
  stage: deploy_stag
  only:
    - stage
  script:
    - pip install awscli
    - aws s3 sync ./build s3://marafeqreact --region me-south-1
  when: manual

deploy_prod:
  image: python:alpine
  stage: deploy_prod
  only:
    - main
  script:
    - pip install awscli
    - aws s3 sync ./build s3://marafeqreact --region me-south-1
  when: manual
